<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260325121409 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Creates forum tables for users, sections, posts, comments and post images.';
    }

    public function up(Schema $schema): void
    {
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform,
            'This migration can only be executed safely on postgresql.'
        );

        $this->addSql(<<<'SQL'
            CREATE TABLE users (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              email VARCHAR(180) NOT NULL,
              roles JSON NOT NULL,
              password VARCHAR(255) NOT NULL,
              display_name VARCHAR(100) NOT NULL,
              avatar_filename VARCHAR(255) DEFAULT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              PRIMARY KEY(id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E9E7927C74 ON users (email)');
        $this->addSql(<<<'SQL'
            CREATE TABLE section (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              name VARCHAR(100) NOT NULL,
              description TEXT DEFAULT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              PRIMARY KEY(id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2D737AEF5E237E06 ON section (name)');
        $this->addSql(<<<'SQL'
            CREATE TABLE post (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              section_id INT NOT NULL,
              author_id INT NOT NULL,
              text TEXT NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              PRIMARY KEY(id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_5A8A6C8DD823E37A ON post (section_id)');
        $this->addSql('CREATE INDEX IDX_5A8A6C8DF675F31B ON post (author_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE post_image (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              post_id INT NOT NULL,
              filename VARCHAR(255) NOT NULL,
              original_name VARCHAR(255) NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              PRIMARY KEY(id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_522688B04B89032C ON post_image (post_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE comment (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              post_id INT NOT NULL,
              author_id INT NOT NULL,
              text TEXT NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              PRIMARY KEY(id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_9474526C4B89032C ON comment (post_id)');
        $this->addSql('CREATE INDEX IDX_9474526CF675F31B ON comment (author_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE section_moderators (
              section_id INT NOT NULL,
              user_id INT NOT NULL,
              PRIMARY KEY (section_id, user_id),
              CONSTRAINT FK_C5BD2C0CD823E37A FOREIGN KEY (section_id) REFERENCES section (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE,
              CONSTRAINT FK_C5BD2C0CA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_C5BD2C0CD823E37A ON section_moderators (section_id)');
        $this->addSql('CREATE INDEX IDX_C5BD2C0CA76ED395 ON section_moderators (user_id)');
        $this->addSql('ALTER TABLE post ADD CONSTRAINT FK_5A8A6C8DD823E37A FOREIGN KEY (section_id) REFERENCES section (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE post ADD CONSTRAINT FK_5A8A6C8DF675F31B FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE post_image ADD CONSTRAINT FK_522688B04B89032C FOREIGN KEY (post_id) REFERENCES post (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE comment ADD CONSTRAINT FK_9474526C4B89032C FOREIGN KEY (post_id) REFERENCES post (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE comment ADD CONSTRAINT FK_9474526CF675F31B FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform,
            'This migration can only be executed safely on postgresql.'
        );

        $this->addSql('DROP TABLE comment');
        $this->addSql('DROP TABLE post_image');
        $this->addSql('DROP TABLE post');
        $this->addSql('DROP TABLE section_moderators');
        $this->addSql('DROP TABLE section');
        $this->addSql('DROP TABLE users');
    }
}
